#! /bin/sh
# Test ex12a

NAME=ex12a
DB=phreeqc.dat

if [ ! -e ../database/phreeqc.dat ]
then
  DBCOPIED=Yes
  cp $DBDIR/$DB ../database/.
fi

: ${PHREEQC=phreeqc}
${PHREEQC} $DATADIR/$NAME $NAME.out $DBDIR/$DB $NAME.log
result=$?

if [ "$DBCOPIED" == "Yes" ]
then
  rm ../database/$DB
fi

exit $result
