#! /bin/sh

if [ ! -f doc/README ];then
  ln -s README.Linux.txt doc/README
fi

if [ ! -f doc/RELEASE ];then
  ln -s RELEASE.TXT doc/RELEASE
fi

if [ ! -f doc/NOTICE ];then
  ln -s NOTICE.TXT doc/NOTICE
fi

exec autoreconf -fvi

