(define (script-fu-scale-files)
  (scale-fifty-percent "phreeqc3-1.png")
  (scale-fifty-percent "phreeqc3-2.png")
  (scale-fifty-percent "phreeqc3-3.png")
  (scale-fifty-percent "phreeqc3-4.png")
  (scale-fifty-percent "phreeqc3-5.png")
  (scale-fifty-percent "phreeqc3-6.png")
  (scale-fifty-percent "phreeqc3-7.png")
  (scale-fifty-percent "phreeqc3-8.png")
  (scale-fifty-percent "phreeqc3-9.png")
  (scale-fifty-percent "phreeqc3-10.png")
  (scale-fifty-percent "phreeqc3-11.png")
  (scale-fifty-percent "phreeqc3-12.png")
  (scale-fifty-percent "phreeqc3-13.png")
  (scale-fifty-percent "phreeqc3-14.png")
  (scale-fifty-percent "phreeqc3-15.png")
  (scale-fifty-percent "phreeqc3-16.png")
  (scale-fifty-percent "phreeqc3-17.png")
  (scale-fifty-percent "phreeqc3-18.png")
  (scale-fifty-percent "phreeqc3-19.png")
  (scale-fifty-percent "phreeqc3-20.png")
  (scale-fifty-percent "phreeqc3-21.png")
  (scale-fifty-percent "phreeqc3-22.png")
  (scale-fifty-percent "phreeqc3-23.png")
  (scale-fifty-percent "phreeqc3-24.png")
  (scale-fifty-percent "phreeqc3-25.png")
  (scale-fifty-percent "phreeqc3-26.png")
  (scale-fifty-percent "phreeqc3-27.png")
  (scale-fifty-percent "phreeqc3-28.png")
  (scale-fifty-percent "phreeqc3-29.png")
  (scale-fifty-percent "phreeqc3-30.png")
  (scale-fifty-percent "phreeqc3-31.png")
  (scale-fifty-percent "phreeqc3-32.png")
  (scale-fifty-percent "phreeqc3-33.png")
  (scale-fifty-percent "phreeqc3-34.png")
  (scale-fifty-percent "phreeqc3-35.png")
  (scale-fifty-percent "phreeqc3-36.png")
  (scale-fifty-percent "phreeqc3-37.png")
  (scale-fifty-percent "phreeqc3-38.png")
  (scale-fifty-percent "phreeqc3-39.png")
  (scale-fifty-percent "phreeqc3-40.png")
  (scale-fifty-percent "phreeqc3-41.png")
  (scale-fifty-percent "phreeqc3-42.png")
  (scale-fifty-percent "phreeqc3-43.png")
  (scale-fifty-percent "phreeqc3-44.png")
  (scale-fifty-percent "phreeqc3-45.png")
  (scale-fifty-percent "phreeqc3-46.png")
  (scale-fifty-percent "phreeqc3-47.png")
  (scale-fifty-percent "phreeqc3-48.png")
  (scale-fifty-percent "phreeqc3-49.png")
  (scale-fifty-percent "phreeqc3-50.png")
  (scale-fifty-percent "phreeqc3-51.png")
  (scale-fifty-percent "phreeqc3-52.png")
  (scale-fifty-percent "phreeqc3-53.png")
  (scale-fifty-percent "phreeqc3-54.png")
  (scale-fifty-percent "phreeqc3-55.png")
  (scale-fifty-percent "phreeqc3-56.png")
  (scale-fifty-percent "phreeqc3-57.png")
  (scale-fifty-percent "phreeqc3-58.png")
  (scale-fifty-percent "phreeqc3-59.png")
  (scale-fifty-percent "phreeqc3-60.png")
  (scale-fifty-percent "phreeqc3-61.png")
  (scale-fifty-percent "phreeqc3-62.png")
  (scale-fifty-percent "phreeqc3-63.png")
  (scale-fifty-percent "phreeqc3-64.png")
  (scale-fifty-percent "phreeqc3-65.png")
  (scale-fifty-percent "phreeqc3-66.png")
  (scale-fifty-percent "phreeqc3-67.png")
  (scale-fifty-percent "phreeqc3-68.png")
  (scale-fifty-percent "phreeqc3-69.png")
  (scale-fifty-percent "phreeqc3-70.png")
  (scale-fifty-percent "phreeqc3-71.png")
  (scale-fifty-percent "phreeqc3-72.png")
  (scale-fifty-percent "phreeqc3-73.png")
  (scale-fifty-percent "phreeqc3-74.png")
  (scale-fifty-percent "phreeqc3-75.png")
  (scale-fifty-percent "phreeqc3-76.png")
  (scale-fifty-percent "phreeqc3-77.png")
  (scale-fifty-percent "phreeqc3-78.png")
  (scale-fifty-percent "phreeqc3-79.png")
  (scale-fifty-percent "phreeqc3-80.png")
  (scale-fifty-percent "phreeqc3-81.png")
  (scale-fifty-percent "phreeqc3-82.png")
  (scale-fifty-percent "phreeqc3-83.png")
  (scale-fifty-percent "phreeqc3-84.png")
  (scale-fifty-percent "phreeqc3-85.png")
  (scale-fifty-percent "phreeqc3-86.png")
  (scale-fifty-percent "phreeqc3-87.png")
  (scale-fifty-percent "phreeqc3-88.png")
  (scale-fifty-percent "phreeqc3-89.png")
  (scale-fifty-percent "phreeqc3-90.png")
  (scale-fifty-percent "phreeqc3-91.png")
  (scale-fifty-percent "phreeqc3-92.png")
  (scale-fifty-percent "phreeqc3-93.png")
  (scale-fifty-percent "phreeqc3-94.png")
  (scale-fifty-percent "phreeqc3-95.png")
  (scale-fifty-percent "phreeqc3-96.png")
  (scale-fifty-percent "phreeqc3-97.png")
  (scale-fifty-percent "phreeqc3-98.png")
  (scale-fifty-percent "phreeqc3-99.png")
  (scale-fifty-percent "phreeqc3-100.png")
  (scale-fifty-percent "phreeqc3-101.png")
  (scale-fifty-percent "phreeqc3-102.png")
  (scale-fifty-percent "phreeqc3-103.png")
  (scale-fifty-percent "phreeqc3-104.png")
  (scale-fifty-percent "phreeqc3-105.png")
  (scale-fifty-percent "phreeqc3-106.png")
  (scale-fifty-percent "phreeqc3-107.png")
  (scale-fifty-percent "phreeqc3-108.png")
  (scale-fifty-percent "phreeqc3-109.png")
  (scale-fifty-percent "phreeqc3-110.png")
  (scale-fifty-percent "phreeqc3-111.png")
  (scale-fifty-percent "phreeqc3-112.png")
  (scale-fifty-percent "phreeqc3-113.png")
  (scale-fifty-percent "phreeqc3-114.png")
  (scale-fifty-percent "phreeqc3-115.png")
  (scale-fifty-percent "phreeqc3-116.png")
  (scale-fifty-percent "phreeqc3-117.png")
  (scale-fifty-percent "phreeqc3-118.png")
  (scale-fifty-percent "phreeqc3-119.png")
  (scale-fifty-percent "phreeqc3-120.png")
  (scale-fifty-percent "phreeqc3-121.png")
  (scale-fifty-percent "phreeqc3-122.png")
  (scale-fifty-percent "phreeqc3-123.png")
  (scale-fifty-percent "phreeqc3-124.png")
  (scale-fifty-percent "phreeqc3-125.png")
  (scale-fifty-percent "phreeqc3-126.png")
  (scale-fifty-percent "phreeqc3-127.png")
  (scale-fifty-percent "phreeqc3-128.png")
  (scale-fifty-percent "phreeqc3-129.png")
  (scale-fifty-percent "phreeqc3-130.png")
  (scale-fifty-percent "phreeqc3-131.png")
  (scale-fifty-percent "phreeqc3-132.png")
  (scale-fifty-percent "phreeqc3-133.png")
  (scale-fifty-percent "phreeqc3-134.png")
  (scale-fifty-percent "phreeqc3-135.png")
  (scale-fifty-percent "phreeqc3-136.png")
  (scale-fifty-percent "phreeqc3-137.png")
  (scale-fifty-percent "phreeqc3-138.png")
  (scale-fifty-percent "phreeqc3-139.png")
  (scale-fifty-percent "phreeqc3-140.png")
  (scale-fifty-percent "phreeqc3-141.png")
  (scale-fifty-percent "phreeqc3-142.png")
  (scale-fifty-percent "phreeqc3-143.png")
  (scale-fifty-percent "phreeqc3-144.png")
  (scale-fifty-percent "phreeqc3-145.png")
  (scale-fifty-percent "phreeqc3-146.png")
  (scale-fifty-percent "phreeqc3-147.png")
  (scale-fifty-percent "phreeqc3-148.png")
  (scale-fifty-percent "phreeqc3-149.png")
  (scale-fifty-percent "phreeqc3-150.png")
  (scale-fifty-percent "phreeqc3-151.png")
  (scale-fifty-percent "phreeqc3-152.png")
  (scale-fifty-percent "phreeqc3-153.png")
  (scale-fifty-percent "phreeqc3-154.png")
  (scale-fifty-percent "phreeqc3-155.png")
  (scale-fifty-percent "phreeqc3-156.png")
  (scale-fifty-percent "phreeqc3-157.png")
  (scale-fifty-percent "phreeqc3-158.png")
  (scale-fifty-percent "phreeqc3-159.png")
  (scale-fifty-percent "phreeqc3-160.png")
  (scale-fifty-percent "phreeqc3-161.png")
  (scale-fifty-percent "phreeqc3-162.png")
  (scale-fifty-percent "phreeqc3-163.png")
  (scale-fifty-percent "phreeqc3-164.png")
  (scale-fifty-percent "phreeqc3-165.png")
  (scale-fifty-percent "phreeqc3-166.png")
  (scale-fifty-percent "phreeqc3-167.png")
  (scale-fifty-percent "phreeqc3-168.png")
  (scale-fifty-percent "phreeqc3-169.png")
  (scale-fifty-percent "phreeqc3-170.png")
  (scale-fifty-percent "phreeqc3-171.png")
  (scale-fifty-percent "phreeqc3-172.png")
  (scale-fifty-percent "phreeqc3-173.png")
  (scale-fifty-percent "phreeqc3-174.png")
  (scale-fifty-percent "phreeqc3-175.png")
  (scale-fifty-percent "phreeqc3-176.png")
  (scale-fifty-percent "phreeqc3-177.png")
  (scale-fifty-percent "phreeqc3-178.png")
  (scale-fifty-percent "phreeqc3-179.png")
  (scale-fifty-percent "phreeqc3-180.png")
  (scale-fifty-percent "phreeqc3-181.png")
  (scale-fifty-percent "phreeqc3-182.png")
  (scale-fifty-percent "phreeqc3-183.png")
  (scale-fifty-percent "phreeqc3-184.png")
  (scale-fifty-percent "phreeqc3-185.png")
  (scale-fifty-percent "phreeqc3-186.png")
  (scale-fifty-percent "phreeqc3-187.png")
  (scale-fifty-percent "phreeqc3-188.png")
  (scale-fifty-percent "phreeqc3-189.png")
  (scale-fifty-percent "phreeqc3-190.png")
  (scale-fifty-percent "phreeqc3-191.png")
  (scale-fifty-percent "phreeqc3-192.png")
  (scale-fifty-percent "phreeqc3-193.png")
  (scale-fifty-percent "phreeqc3-194.png")
  (scale-fifty-percent "phreeqc3-195.png")
  (scale-fifty-percent "phreeqc3-196.png")
  (scale-fifty-percent "phreeqc3-197.png")
  (scale-fifty-percent "phreeqc3-198.png")
  (scale-fifty-percent "phreeqc3-199.png")
  (scale-fifty-percent "phreeqc3-200.png")
  (scale-fifty-percent "phreeqc3-201.png")
  (scale-fifty-percent "phreeqc3-202.png")
  (scale-fifty-percent "phreeqc3-203.png")
  (scale-fifty-percent "phreeqc3-204.png")
  (scale-fifty-percent "phreeqc3-205.png")
  (scale-fifty-percent "phreeqc3-206.png")
  (scale-fifty-percent "phreeqc3-207.png")
  (scale-fifty-percent "phreeqc3-208.png")
  (scale-fifty-percent "phreeqc3-209.png")
  (scale-fifty-percent "phreeqc3-213.png")
  (scale-fifty-percent "phreeqc3-214.png")
  (scale-fifty-percent "phreeqc3-215.png")
  (scale-fifty-percent "phreeqc3-216.png")
  (scale-fifty-percent "phreeqc3-217.png")
  (scale-fifty-percent "phreeqc3-218.png")
  (scale-fifty-percent "phreeqc3-221.png")
  (scale-fifty-percent "phreeqc3-222.png")
  (scale-fifty-percent "phreeqc3-223.png")
  (scale-fifty-percent "phreeqc3-224.png")
  (scale-fifty-percent "phreeqc3-225.png")
  (scale-fifty-percent "phreeqc3-227.png")
  (scale-fifty-percent "phreeqc3-229.png")
  (scale-fifty-percent "phreeqc3-230.png")
  (scale-fifty-percent "phreeqc3-231.png")
  (scale-fifty-percent "phreeqc3-234.png")
  (scale-fifty-percent "phreeqc3-235.png")
  (scale-fifty-percent "phreeqc3-236.png")
  (scale-fifty-percent "phreeqc3-237.png")
  (scale-fifty-percent "phreeqc3-238.png")
  (scale-fifty-percent "phreeqc3-240.png")
  (scale-fifty-percent "phreeqc3-241.png")
  (scale-fifty-percent "phreeqc3-242.png")
  (scale-fifty-percent "phreeqc3-243.png")
  (scale-fifty-percent "phreeqc3-244.png")
  (scale-fifty-percent "phreeqc3-246.png")
  (scale-fifty-percent "phreeqc3-248.png")
  (scale-fifty-percent "phreeqc3-249.png")
  (scale-fifty-percent "phreeqc3-250.png")
  (scale-fifty-percent "phreeqc3-251.png")
  (scale-fifty-percent "phreeqc3-252.png")
  (scale-fifty-percent "phreeqc3-253.png")
  (scale-fifty-percent "phreeqc3-254.png")
  (scale-fifty-percent "phreeqc3-255.png")
  (scale-fifty-percent "phreeqc3-256.png")
  (scale-fifty-percent "phreeqc3-258.png")
  (scale-fifty-percent "phreeqc3-259.png")
  (scale-fifty-percent "phreeqc3-260.png")
  (scale-fifty-percent "phreeqc3-261.png")
  (scale-fifty-percent "phreeqc3-262.png")
  (scale-fifty-percent "phreeqc3-263.png")
  (scale-fifty-percent "phreeqc3-265.png")
  (scale-fifty-percent "phreeqc3-267.png")
  (scale-fifty-percent "phreeqc3-268.png")
  (scale-fifty-percent "phreeqc3-269.png")
  (scale-fifty-percent "phreeqc3-270.png")
  (scale-fifty-percent "phreeqc3-271.png")
  (scale-fifty-percent "phreeqc3-272.png")
  (scale-fifty-percent "phreeqc3-273.png")
  (scale-fifty-percent "phreeqc3-274.png")
  (scale-fifty-percent "phreeqc3-275.png")
  (scale-fifty-percent "phreeqc3-276.png")
  (scale-fifty-percent "phreeqc3-277.png")
  (scale-fifty-percent "phreeqc3-281.png")
  (scale-fifty-percent "phreeqc3-282.png")
  (scale-fifty-percent "phreeqc3-283.png")
  (scale-fifty-percent "phreeqc3-284.png")
  (scale-fifty-percent "phreeqc3-285.png")
  (scale-fifty-percent "phreeqc3-286.png")
  (scale-fifty-percent "phreeqc3-287.png")
  (scale-fifty-percent "phreeqc3-288.png")
  (scale-fifty-percent "phreeqc3-289.png")
  (scale-fifty-percent "phreeqc3-290.png")
  (scale-fifty-percent "phreeqc3-291.png")
  (scale-fifty-percent "phreeqc3-292.png")
  (scale-fifty-percent "phreeqc3-293.png")
  (scale-fifty-percent "phreeqc3-294.png")
  (scale-fifty-percent "phreeqc3-295.png")
  (scale-fifty-percent "phreeqc3-296.png")
  (scale-fifty-percent "phreeqc3-297.png")
  (scale-fifty-percent "phreeqc3-298.png")
  (scale-fifty-percent "phreeqc3-299.png")
  (scale-fifty-percent "phreeqc3-300.png")
  (scale-fifty-percent "phreeqc3-301.png")
  (scale-fifty-percent "phreeqc3-302.png")
  (scale-fifty-percent "phreeqc3-303.png")
  (scale-fifty-percent "phreeqc3-304.png")
  (scale-fifty-percent "phreeqc3-305.png")
  (scale-fifty-percent "phreeqc3-306.png")
  (scale-fifty-percent "phreeqc3-307.png")
  (scale-fifty-percent "phreeqc3-308.png")
  (scale-fifty-percent "phreeqc3-309.png")
  (scale-fifty-percent "phreeqc3-310.png")
  (scale-fifty-percent "phreeqc3-311.png")
  (scale-fifty-percent "phreeqc3-312.png")
  (scale-fifty-percent "phreeqc3-313.png")
  (scale-fifty-percent "phreeqc3-314.png")
  (scale-fifty-percent "phreeqc3-315.png")
  (scale-fifty-percent "phreeqc3-316.png")
  (scale-fifty-percent "phreeqc3-317.png")
  (scale-fifty-percent "phreeqc3-318.png")
  (scale-fifty-percent "phreeqc3-319.png")
  (scale-fifty-percent "phreeqc3-320.png")
  (scale-fifty-percent "phreeqc3-321.png")
  (scale-fifty-percent "phreeqc3-322.png")
  (scale-fifty-percent "phreeqc3-323.png")
  (scale-fifty-percent "phreeqc3-324.png")
  (scale-fifty-percent "phreeqc3-326.png")
  (scale-fifty-percent "phreeqc3-327.png")
  (scale-fifty-percent "phreeqc3-328.png")
  (scale-fifty-percent "phreeqc3-329.png")
  (scale-fifty-percent "phreeqc3-330.png")
  (scale-fifty-percent "phreeqc3-332.png")
  (scale-fifty-percent "phreeqc3-333.png")
  (scale-fifty-percent "phreeqc3-334.png")
  (scale-fifty-percent "phreeqc3-335.png")
  (scale-fifty-percent "phreeqc3-337.png")
  (scale-fifty-percent "phreeqc3-338.png")
  (scale-fifty-percent "phreeqc3-339.png")
  (scale-fifty-percent "phreeqc3-340.png")
  (scale-fifty-percent "phreeqc3-341.png")
  (scale-fifty-percent "phreeqc3-342.png")
  (scale-fifty-percent "phreeqc3-343.png")
  (scale-fifty-percent "phreeqc3-344.png")
  (scale-fifty-percent "phreeqc3-345.png")
  (scale-fifty-percent "phreeqc3-346.png")
  (scale-fifty-percent "phreeqc3-347.png")
  (scale-fifty-percent "phreeqc3-348.png")
  (scale-fifty-percent "phreeqc3-352.png")
  )

(script-fu-register
 "script-fu-scale-files"
 "<Image>/Xtns/Scale-Fifty"
 "Scales images 50 percent"
 "Scott Charlton"
 "copyright 1999, Scott Charlton"
 "December 9, 1999"
 ""
 )

(define (scale-fifty-percent filename)
  (let*
      (
       (width 0)
       (height 0)
       (new_width 0)
       (new_height 0)
       (drw 0)
       (noExt " ")
       (image 0)
       (layer 0)
       (display 0)
       (drw 0)
       )
    (set! image (car (gimp-file-load RUN-NONINTERACTIVE filename filename)))
    (set! layer (car (gimp-image-get-active-layer image)))
    (set! display (car (gimp-display-new image)))
    (set! width (car (gimp-image-width image)))
    (set! height (car (gimp-image-height image)))
    (set! new_width (/ width 2))
    (set! new_height (/ height 2))
    (gimp-image-scale image new_width new_height)
    (set! drw (car (gimp-image-flatten image)))
    (file-png-save RUN-NONINTERACTIVE
		   image
		   drw
		   filename
		   filename
		   0
		   5
		   0
		   0
		   0
		   0
		   0)
    (gimp-display-delete display)
    )
  )