2.14               # File format
1. Solution 34
       -1.#IND     # C
       -1.#IND     # S
       -1.#IND     # CA
       -1.#IND     # AL
       -1.#IND     # MG
       -1.#IND     # NA
       -1.#IND     # K
       -1.#IND     # CL
       -1.#IND     # F
       -1.#IND     # SI
       -1.#IND     # BR
       -1.#IND     # B
       -1.#IND     # BA
       -1.#IND     # LI
       -1.#IND     # SR
       -1.#IND     # FE
       -1.#IND     # MN
       -1.#IND     # N
       -1.#IND     # P
            25     # TEMP
       -1.#IND     # H2S
       -1.#IND     # SO4
             0*    # N15
       -1.#IND     # RS of N
       -1.#IND     # DOX
       4.80351     # HCO3
             6     # PH
        1.#INF     # H2CO3
    0.00839493     # CO3
        1.#INF     # CARBONATES
       -1.#IND     # FE2+
       -1.#IND     # FE3+
       -1.#IND     # MN2+
       -1.#IND     # MN3+
             0*    # MN6+
             0*    # MN7+
       -1.#IND     # CH4
             0*    # DOC
             0*    # RS OF DOC
             0*    # BLANK
       -1.#IND     # C13
       -1.#IND     # C14
             0*    # SR87
             0*    # D
             0*    # O-18
             0*    # TRITIUM
             0*    # 34SSO4
             0*    # 34SH2S
             1     # Well number
1.  01S-02E-01 DCB 1 Harrison, Nace 
       -1.#IND     # C
       -1.#IND     # S
        1.#INF     # CA
       -1.#IND     # AL
        1.#INF     # MG
        1.#INF     # NA
        1.#INF     # K
        1.#INF     # CL
        1.#INF     # F
       -1.#IND     # SI
        1.#INF     # BR
       -1.#IND     # B
        1.#INF     # BA
        1.#INF     # LI
        1.#INF     # SR
       -1.#IND     # FE
       -1.#IND     # MN
       -1.#IND     # N
       -1.#IND     # P
          33.1     # TEMP
       -1.#IND     # H2S
        1.#INF     # SO4
             0*    # N15
       -1.#IND     # RS of N
       -1.#IND     # DOX
       4.80351     # HCO3
           6.5     # PH
        1.#INF     # H2CO3
    0.00839493     # CO3
        1.#INF     # CARBONATES
       -1.#IND     # FE2+
       -1.#IND     # FE3+
       -1.#IND     # MN2+
       -1.#IND     # MN3+
             0*    # MN6+
             0*    # MN7+
       -1.#IND     # CH4
             0*    # DOC
             0*    # RS OF DOC
             0*    # BLANK
       -1.#IND     # C13
       -1.#IND     # C14
             0*    # SR87
       -1.#IND     # D
       -1.#IND     # O-18
             0*    # TRITIUM
             0*    # 34SSO4
             0*    # 34SH2S
             2     # Well number
1.  01S-03E-03 ABA 1        Vendome Well 
       -1.#IND     # C
       -1.#IND     # S
        1.#INF     # CA
       -1.#IND     # AL
        1.#INF     # MG
        1.#INF     # NA
        1.#INF     # K
        1.#INF     # CL
        1.#INF     # F
       -1.#IND     # SI
        1.#INF     # BR
       -1.#IND     # B
        1.#INF     # BA
        1.#INF     # LI
        1.#INF     # SR
       -1.#IND     # FE
       -1.#IND     # MN
       -1.#IND     # N
       -1.#IND     # P
          19.6     # TEMP
       -1.#IND     # H2S
        1.#INF     # SO4
             0*    # N15
       -1.#IND     # RS of N
       -1.#IND     # DOX
       4.80351     # HCO3
          7.14     # PH
        1.#INF     # H2CO3
    0.00839493     # CO3
        1.#INF     # CARBONATES
       -1.#IND     # FE2+
       -1.#IND     # FE3+
       -1.#IND     # MN2+
       -1.#IND     # MN3+
             0*    # MN6+
             0*    # MN7+
       -1.#IND     # CH4
             0*    # DOC
             0*    # RS OF DOC
             0*    # BLANK
       -1.#IND     # C13
       -1.#IND     # C14
             0*    # SR87
       -1.#IND     # D
       -1.#IND     # O-18
             0*    # TRITIUM
             0*    # 34SSO4
             0*    # 34SH2S
             3     # Well number
2. Solution after simulation 3.
       -1.#IND     # C
       -1.#IND     # S
        1.#INF     # CA
       -1.#IND     # AL
        1.#INF     # MG
        1.#INF     # NA
        1.#INF     # K
        1.#INF     # CL
       -1.#IND     # F
       -1.#IND     # SI
       -1.#IND     # BR
       -1.#IND     # B
       -1.#IND     # BA
       -1.#IND     # LI
       -1.#IND     # SR
       -1.#IND     # FE
       -1.#IND     # MN
       -1.#IND     # N
       -1.#IND     # P
            17     # TEMP
       -1.#IND     # H2S
        1.#INF     # SO4
             0*    # N15
       -1.#IND     # RS of N
        1.#INF     # DOX
       4.80351     # HCO3
       7.10266     # PH
        1.#INF     # H2CO3
    0.00839493     # CO3
        1.#INF     # CARBONATES
       -1.#IND     # FE2+
       -1.#IND     # FE3+
       -1.#IND     # MN2+
       -1.#IND     # MN3+
             0*    # MN6+
             0*    # MN7+
       -1.#IND     # CH4
             0*    # DOC
             0*    # RS OF DOC
             0*    # BLANK
       -1.#IND     # C13
       -1.#IND     # C14
             0*    # SR87
             0*    # D
             0*    # O-18
             0*    # TRITIUM
             0*    # 34SSO4
             0*    # 34SH2S
             4     # Well number
2.  01S-02E-01 DCB 1 Harrison, Nace 
       -1.#IND     # C
       -1.#IND     # S
        1.#INF     # CA
       -1.#IND     # AL
        1.#INF     # MG
        1.#INF     # NA
        1.#INF     # K
        1.#INF     # CL
        1.#INF     # F
       -1.#IND     # SI
        1.#INF     # BR
       -1.#IND     # B
        1.#INF     # BA
        1.#INF     # LI
        1.#INF     # SR
       -1.#IND     # FE
       -1.#IND     # MN
       -1.#IND     # N
       -1.#IND     # P
          33.1     # TEMP
       -1.#IND     # H2S
        1.#INF     # SO4
             0*    # N15
       -1.#IND     # RS of N
       -1.#IND     # DOX
       4.80351     # HCO3
           6.5     # PH
        1.#INF     # H2CO3
    0.00839493     # CO3
        1.#INF     # CARBONATES
       -1.#IND     # FE2+
       -1.#IND     # FE3+
       -1.#IND     # MN2+
       -1.#IND     # MN3+
             0*    # MN6+
             0*    # MN7+
       -1.#IND     # CH4
             0*    # DOC
             0*    # RS OF DOC
             0*    # BLANK
       -1.#IND     # C13
       -1.#IND     # C14
             0*    # SR87
       -1.#IND     # D
       -1.#IND     # O-18
             0*    # TRITIUM
             0*    # 34SSO4
             0*    # 34SH2S
             5     # Well number
2.  01S-03E-03 ABA 1        Vendome Well 
       -1.#IND     # C
       -1.#IND     # S
        1.#INF     # CA
       -1.#IND     # AL
        1.#INF     # MG
        1.#INF     # NA
        1.#INF     # K
        1.#INF     # CL
        1.#INF     # F
       -1.#IND     # SI
        1.#INF     # BR
       -1.#IND     # B
        1.#INF     # BA
        1.#INF     # LI
        1.#INF     # SR
       -1.#IND     # FE
       -1.#IND     # MN
       -1.#IND     # N
       -1.#IND     # P
          19.6     # TEMP
       -1.#IND     # H2S
        1.#INF     # SO4
             0*    # N15
       -1.#IND     # RS of N
       -1.#IND     # DOX
       4.80351     # HCO3
          7.14     # PH
        1.#INF     # H2CO3
    0.00839493     # CO3
        1.#INF     # CARBONATES
       -1.#IND     # FE2+
       -1.#IND     # FE3+
       -1.#IND     # MN2+
       -1.#IND     # MN3+
             0*    # MN6+
             0*    # MN7+
       -1.#IND     # CH4
             0*    # DOC
             0*    # RS OF DOC
             0*    # BLANK
       -1.#IND     # C13
       -1.#IND     # C14
             0*    # SR87
       -1.#IND     # D
       -1.#IND     # O-18
             0*    # TRITIUM
             0*    # 34SSO4
             0*    # 34SH2S
             6     # Well number
