# Makefile.in generated by automake 1.11.1 from Makefile.am.
# src/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




pkgdatadir = $(datadir)/phreeqc
pkgincludedir = $(includedir)/phreeqc
pkglibdir = $(libdir)/phreeqc
pkglibexecdir = $(libexecdir)/phreeqc
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = phreeqc$(EXEEXT)
am__append_1 = \
	cl1mp.cpp

subdir = src
DIST_COMMON = $(srcdir)/Makefile.am $(srcdir)/Makefile.in
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am__phreeqc_SOURCES_DIST = class_main.cpp cxxKinetics.cxx \
	cxxKinetics.h cxxMix.cxx cxxMix.h dumper.cpp dumper.h \
	Exchange.cxx Exchange.h ExchComp.cxx ExchComp.h GasComp.cxx \
	GasComp.h GasPhase.cxx GasPhase.h ISolution.cxx ISolution.h \
	ISolutionComp.cxx ISolutionComp.h Keywords.cpp Keywords.h \
	KineticsComp.cxx KineticsComp.h NameDouble.cxx NameDouble.h \
	NumKeyword.cxx NumKeyword.h Parser.cxx Parser.h PBasic.cpp \
	PBasic.h Phreeqc.cpp Phreeqc.h PHRQ_base.cxx PHRQ_base.h \
	PHRQ_io.cpp PHRQ_io.h PPassemblage.cxx PPassemblage.h \
	PPassemblageComp.cxx PPassemblageComp.h Pressure.cxx \
	Pressure.h Reaction.cxx Reaction.h ReadClass.cxx runner.cpp \
	runner.h SelectedOutput.cpp SelectedOutput.h Solution.cxx \
	Solution.h SolutionIsotope.cxx SolutionIsotope.h \
	SSassemblage.cxx SSassemblage.h SS.cxx SS.h SScomp.cxx \
	SScomp.h StorageBin.cxx StorageBin.h StorageBinList.cpp \
	StorageBinList.h Surface.cxx Surface.h SurfaceCharge.cxx \
	SurfaceCharge.h SurfaceComp.cxx SurfaceComp.h System.cxx \
	System.h Temperature.cxx Temperature.h Use.cpp Use.h \
	UserPunch.cpp UserPunch.h Utils.cxx Utils.h advection.cpp \
	basicsubs.cpp cl1.cpp cvdense.cpp cvdense.h cvode.cpp cvode.h \
	dense.cpp dense.h dw.cpp gases.cpp global_structures.h \
	input.cpp integrate.cpp inverse.cpp isotopes.cpp kinetics.cpp \
	mainsubs.cpp model.cpp NA.h nvector.cpp nvector.h \
	nvector_serial.cpp nvector_serial.h parse.cpp phqalloc.cpp \
	phqalloc.h PHRQ_io_output.cpp phrqtype.h pitzer.cpp \
	pitzer_structures.cpp prep.cpp print.cpp read.cpp readtr.cpp \
	sit.cpp smalldense.cpp smalldense.h spread.cpp step.cpp \
	structures.cpp sundialsmath.cpp sundialsmath.h sundialstypes.h \
	tally.cpp tidy.cpp transport.cpp utilities.cpp cl1mp.cpp
am__objects_1 = cl1mp.$(OBJEXT)
am_phreeqc_OBJECTS = class_main.$(OBJEXT) cxxKinetics.$(OBJEXT) \
	cxxMix.$(OBJEXT) dumper.$(OBJEXT) Exchange.$(OBJEXT) \
	ExchComp.$(OBJEXT) GasComp.$(OBJEXT) GasPhase.$(OBJEXT) \
	ISolution.$(OBJEXT) ISolutionComp.$(OBJEXT) Keywords.$(OBJEXT) \
	KineticsComp.$(OBJEXT) NameDouble.$(OBJEXT) \
	NumKeyword.$(OBJEXT) Parser.$(OBJEXT) PBasic.$(OBJEXT) \
	Phreeqc.$(OBJEXT) PHRQ_base.$(OBJEXT) PHRQ_io.$(OBJEXT) \
	PPassemblage.$(OBJEXT) PPassemblageComp.$(OBJEXT) \
	Pressure.$(OBJEXT) Reaction.$(OBJEXT) ReadClass.$(OBJEXT) \
	runner.$(OBJEXT) SelectedOutput.$(OBJEXT) Solution.$(OBJEXT) \
	SolutionIsotope.$(OBJEXT) SSassemblage.$(OBJEXT) SS.$(OBJEXT) \
	SScomp.$(OBJEXT) StorageBin.$(OBJEXT) StorageBinList.$(OBJEXT) \
	Surface.$(OBJEXT) SurfaceCharge.$(OBJEXT) \
	SurfaceComp.$(OBJEXT) System.$(OBJEXT) Temperature.$(OBJEXT) \
	Use.$(OBJEXT) UserPunch.$(OBJEXT) Utils.$(OBJEXT) \
	advection.$(OBJEXT) basicsubs.$(OBJEXT) cl1.$(OBJEXT) \
	cvdense.$(OBJEXT) cvode.$(OBJEXT) dense.$(OBJEXT) dw.$(OBJEXT) \
	gases.$(OBJEXT) input.$(OBJEXT) integrate.$(OBJEXT) \
	inverse.$(OBJEXT) isotopes.$(OBJEXT) kinetics.$(OBJEXT) \
	mainsubs.$(OBJEXT) model.$(OBJEXT) nvector.$(OBJEXT) \
	nvector_serial.$(OBJEXT) parse.$(OBJEXT) phqalloc.$(OBJEXT) \
	PHRQ_io_output.$(OBJEXT) pitzer.$(OBJEXT) \
	pitzer_structures.$(OBJEXT) prep.$(OBJEXT) print.$(OBJEXT) \
	read.$(OBJEXT) readtr.$(OBJEXT) sit.$(OBJEXT) \
	smalldense.$(OBJEXT) spread.$(OBJEXT) step.$(OBJEXT) \
	structures.$(OBJEXT) sundialsmath.$(OBJEXT) tally.$(OBJEXT) \
	tidy.$(OBJEXT) transport.$(OBJEXT) utilities.$(OBJEXT) \
	$(am__objects_1)
phreeqc_OBJECTS = $(am_phreeqc_OBJECTS)
phreeqc_LDADD = $(LDADD)
am__DEPENDENCIES_1 =
phreeqc_DEPENDENCIES = $(am__DEPENDENCIES_1)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/config/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
SOURCES = $(phreeqc_SOURCES)
DIST_SOURCES = $(am__phreeqc_SOURCES_DIST)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} /raid/home/dlpark/programs/phreeqc3-trunk/config/missing --run aclocal-1.11
AMTAR = ${SHELL} /raid/home/dlpark/programs/phreeqc3-trunk/config/missing --run tar
AUTOCONF = ${SHELL} /raid/home/dlpark/programs/phreeqc3-trunk/config/missing --run autoconf
AUTOHEADER = ${SHELL} /raid/home/dlpark/programs/phreeqc3-trunk/config/missing --run autoheader
AUTOMAKE = ${SHELL} /raid/home/dlpark/programs/phreeqc3-trunk/config/missing --run automake-1.11
AWK = gawk
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"phreeqc\" -DPACKAGE_TARNAME=\"phreeqc\" -DPACKAGE_VERSION=\"3.0.0-7109\" -DPACKAGE_STRING=\"phreeqc\ 3.0.0-7109\" -DPACKAGE_BUGREPORT=\"dlpark@usgs.gov\" -DPACKAGE=\"phreeqc\" -DVERSION=\"3.0.0-7109\" -DNDEBUG=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_FLOAT_H=1 -DHAVE_LIMITS_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STDDEF_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_STDLIB_H=1 -DHAVE_REALLOC=1 -DHAVE_MEMMOVE=1 -DHAVE_MEMSET=1 -DHAVE_STRCHR=1 -DHAVE_STRCSPN=1 -DHAVE_STRTOL=1 -DHAVE_FLOOR=1 -DHAVE_POW=1 -DHAVE_SQRT=1 -DHAVE_ISFINITE=/\*\*/ -DHAVE_FINITE=/\*\*/ -DHAVE_ISNAN=1 -DINVERSE_CL1MP=1
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBGMP = -lgmp
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /raid/home/dlpark/programs/phreeqc3-trunk/config/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = phreeqc
PACKAGE_BUGREPORT = dlpark@usgs.gov
PACKAGE_NAME = phreeqc
PACKAGE_STRING = phreeqc 3.0.0-7109
PACKAGE_TARNAME = phreeqc
PACKAGE_VERSION = 3.0.0-7109
PATH_SEPARATOR = :
POW_LIB = 
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 3.0.0-7109
abs_builddir = /raid/home/dlpark/programs/phreeqc3-trunk/src
abs_srcdir = /raid/home/dlpark/programs/phreeqc3-trunk/src
abs_top_builddir = /raid/home/dlpark/programs/phreeqc3-trunk
abs_top_srcdir = /raid/home/dlpark/programs/phreeqc3-trunk
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /raid/home/dlpark/programs/phreeqc3-trunk/config/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = ../
top_builddir = ..
top_srcdir = ..
AM_CPPFLAGS = -I$(top_srcdir)/src -I$(top_srcdir)/src/phreeqc

# sources for phreeqc
phreeqc_SOURCES = class_main.cpp cxxKinetics.cxx cxxKinetics.h \
	cxxMix.cxx cxxMix.h dumper.cpp dumper.h Exchange.cxx \
	Exchange.h ExchComp.cxx ExchComp.h GasComp.cxx GasComp.h \
	GasPhase.cxx GasPhase.h ISolution.cxx ISolution.h \
	ISolutionComp.cxx ISolutionComp.h Keywords.cpp Keywords.h \
	KineticsComp.cxx KineticsComp.h NameDouble.cxx NameDouble.h \
	NumKeyword.cxx NumKeyword.h Parser.cxx Parser.h PBasic.cpp \
	PBasic.h Phreeqc.cpp Phreeqc.h PHRQ_base.cxx PHRQ_base.h \
	PHRQ_io.cpp PHRQ_io.h PPassemblage.cxx PPassemblage.h \
	PPassemblageComp.cxx PPassemblageComp.h Pressure.cxx \
	Pressure.h Reaction.cxx Reaction.h ReadClass.cxx runner.cpp \
	runner.h SelectedOutput.cpp SelectedOutput.h Solution.cxx \
	Solution.h SolutionIsotope.cxx SolutionIsotope.h \
	SSassemblage.cxx SSassemblage.h SS.cxx SS.h SScomp.cxx \
	SScomp.h StorageBin.cxx StorageBin.h StorageBinList.cpp \
	StorageBinList.h Surface.cxx Surface.h SurfaceCharge.cxx \
	SurfaceCharge.h SurfaceComp.cxx SurfaceComp.h System.cxx \
	System.h Temperature.cxx Temperature.h Use.cpp Use.h \
	UserPunch.cpp UserPunch.h Utils.cxx Utils.h advection.cpp \
	basicsubs.cpp cl1.cpp cvdense.cpp cvdense.h cvode.cpp cvode.h \
	dense.cpp dense.h dw.cpp gases.cpp global_structures.h \
	input.cpp integrate.cpp inverse.cpp isotopes.cpp kinetics.cpp \
	mainsubs.cpp model.cpp NA.h nvector.cpp nvector.h \
	nvector_serial.cpp nvector_serial.h parse.cpp phqalloc.cpp \
	phqalloc.h PHRQ_io_output.cpp phrqtype.h pitzer.cpp \
	pitzer_structures.cpp prep.cpp print.cpp read.cpp readtr.cpp \
	sit.cpp smalldense.cpp smalldense.h spread.cpp step.cpp \
	structures.cpp sundialsmath.cpp sundialsmath.h sundialstypes.h \
	tally.cpp tidy.cpp transport.cpp utilities.cpp $(am__append_1)
LDADD = $(LIBGMP)
all: all-am

.SUFFIXES:
.SUFFIXES: .cpp .cxx .o .obj
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign src/Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign src/Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
phreeqc$(EXEEXT): $(phreeqc_OBJECTS) $(phreeqc_DEPENDENCIES) 
	@rm -f phreeqc$(EXEEXT)
	$(CXXLINK) $(phreeqc_OBJECTS) $(phreeqc_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/ExchComp.Po
include ./$(DEPDIR)/Exchange.Po
include ./$(DEPDIR)/GasComp.Po
include ./$(DEPDIR)/GasPhase.Po
include ./$(DEPDIR)/ISolution.Po
include ./$(DEPDIR)/ISolutionComp.Po
include ./$(DEPDIR)/Keywords.Po
include ./$(DEPDIR)/KineticsComp.Po
include ./$(DEPDIR)/NameDouble.Po
include ./$(DEPDIR)/NumKeyword.Po
include ./$(DEPDIR)/PBasic.Po
include ./$(DEPDIR)/PHRQ_base.Po
include ./$(DEPDIR)/PHRQ_io.Po
include ./$(DEPDIR)/PHRQ_io_output.Po
include ./$(DEPDIR)/PPassemblage.Po
include ./$(DEPDIR)/PPassemblageComp.Po
include ./$(DEPDIR)/Parser.Po
include ./$(DEPDIR)/Phreeqc.Po
include ./$(DEPDIR)/Pressure.Po
include ./$(DEPDIR)/Reaction.Po
include ./$(DEPDIR)/ReadClass.Po
include ./$(DEPDIR)/SS.Po
include ./$(DEPDIR)/SSassemblage.Po
include ./$(DEPDIR)/SScomp.Po
include ./$(DEPDIR)/SelectedOutput.Po
include ./$(DEPDIR)/Solution.Po
include ./$(DEPDIR)/SolutionIsotope.Po
include ./$(DEPDIR)/StorageBin.Po
include ./$(DEPDIR)/StorageBinList.Po
include ./$(DEPDIR)/Surface.Po
include ./$(DEPDIR)/SurfaceCharge.Po
include ./$(DEPDIR)/SurfaceComp.Po
include ./$(DEPDIR)/System.Po
include ./$(DEPDIR)/Temperature.Po
include ./$(DEPDIR)/Use.Po
include ./$(DEPDIR)/UserPunch.Po
include ./$(DEPDIR)/Utils.Po
include ./$(DEPDIR)/advection.Po
include ./$(DEPDIR)/basicsubs.Po
include ./$(DEPDIR)/cl1.Po
include ./$(DEPDIR)/cl1mp.Po
include ./$(DEPDIR)/class_main.Po
include ./$(DEPDIR)/cvdense.Po
include ./$(DEPDIR)/cvode.Po
include ./$(DEPDIR)/cxxKinetics.Po
include ./$(DEPDIR)/cxxMix.Po
include ./$(DEPDIR)/dense.Po
include ./$(DEPDIR)/dumper.Po
include ./$(DEPDIR)/dw.Po
include ./$(DEPDIR)/gases.Po
include ./$(DEPDIR)/input.Po
include ./$(DEPDIR)/integrate.Po
include ./$(DEPDIR)/inverse.Po
include ./$(DEPDIR)/isotopes.Po
include ./$(DEPDIR)/kinetics.Po
include ./$(DEPDIR)/mainsubs.Po
include ./$(DEPDIR)/model.Po
include ./$(DEPDIR)/nvector.Po
include ./$(DEPDIR)/nvector_serial.Po
include ./$(DEPDIR)/parse.Po
include ./$(DEPDIR)/phqalloc.Po
include ./$(DEPDIR)/pitzer.Po
include ./$(DEPDIR)/pitzer_structures.Po
include ./$(DEPDIR)/prep.Po
include ./$(DEPDIR)/print.Po
include ./$(DEPDIR)/read.Po
include ./$(DEPDIR)/readtr.Po
include ./$(DEPDIR)/runner.Po
include ./$(DEPDIR)/sit.Po
include ./$(DEPDIR)/smalldense.Po
include ./$(DEPDIR)/spread.Po
include ./$(DEPDIR)/step.Po
include ./$(DEPDIR)/structures.Po
include ./$(DEPDIR)/sundialsmath.Po
include ./$(DEPDIR)/tally.Po
include ./$(DEPDIR)/tidy.Po
include ./$(DEPDIR)/transport.Po
include ./$(DEPDIR)/utilities.Po

.cpp.o:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cxx.o:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cxx.obj:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am check check-am clean clean-binPROGRAMS \
	clean-generic ctags distclean distclean-compile \
	distclean-generic distclean-tags distdir dvi dvi-am html \
	html-am info info-am install install-am install-binPROGRAMS \
	install-data install-data-am install-dvi install-dvi-am \
	install-exec install-exec-am install-html install-html-am \
	install-info install-info-am install-man install-pdf \
	install-pdf-am install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-binPROGRAMS


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
