

USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -0 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -5.0000e-01 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -1 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -1.5000e+00 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -2 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -2.5000e+00 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -3 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -3.5000e+00 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -4 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -4.5000e+00 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -5 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -5.5000e+00 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -6 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -6.5000e+00 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -7 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -7.5000e+00 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -8 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -8.5000e+00 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -9 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -9.5000e+00 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -10 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -1.0500e+01 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -11 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -1.1500e+01 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -12 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -1.2500e+01 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -13 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -1.3500e+01 LiOH 10	
USE kinetics 1	        
END	
USE solution 1	
EQUILIBRIUM_PHASES 1	      
 LiBr	
 Fix_pH -14 LiOH 10	
USE kinetics 1	        
END	
