..\x64\ClrRelease\phreeqc.exe    cc_P
..\x64\ClrRelease\phreeqc.exe    CH4_conc_PR_IS
..\x64\ClrRelease\phreeqc.exe    CO2_4M_NaCl
..\x64\ClrRelease\phreeqc.exe    CO2_anal
..\x64\ClrRelease\phreeqc.exe    CO2_conc_PR_EQ
..\x64\ClrRelease\phreeqc.exe    CO2_conc_PR_GP
..\x64\ClrRelease\phreeqc.exe    CO2_conc_PR_IS
..\x64\ClrRelease\phreeqc.exe    CO2_K_H
..\x64\ClrRelease\phreeqc.exe    CO2_Na2SO4
..\x64\ClrRelease\phreeqc.exe    CO2_sp_IS
..\x64\ClrRelease\phreeqc.exe    co2_t30
..\x64\ClrRelease\phreeqc.exe    co2_tc
..\x64\ClrRelease\phreeqc.exe    co2_VP
..\x64\ClrRelease\phreeqc.exe    fix_P
..\x64\ClrRelease\phreeqc.exe    fix_V
..\x64\ClrRelease\phreeqc.exe    gas_fix_P
..\x64\ClrRelease\phreeqc.exe    gas_fix_V
..\x64\ClrRelease\phreeqc.exe    gypsum_P
..\x64\ClrRelease\phreeqc.exe    gypsum_P2
..\x64\ClrRelease\phreeqc.exe    Hebach
..\x64\ClrRelease\phreeqc.exe    McBride_rho
..\x64\ClrRelease\phreeqc.exe    mV_SO4_rho
..\x64\ClrRelease\phreeqc.exe    mV1_rho
..\x64\ClrRelease\phreeqc.exe    mV2_rho
..\x64\ClrRelease\phreeqc.exe    N2_conc_PR_IS
..\x64\ClrRelease\phreeqc.exe    NaCl
..\x64\ClrRelease\phreeqc.exe    O2_conc_PR_IS
..\x64\ClrRelease\phreeqc.exe    P_CO2_Na2SO4
..\x64\ClrRelease\phreeqc.exe    P_Vm
..\x64\ClrRelease\phreeqc.exe    phi_Angus
..\x64\ClrRelease\phreeqc.exe    phi_CO2-CH4_GP
..\x64\ClrRelease\phreeqc.exe    phi_Duan_PR
..\x64\ClrRelease\phreeqc.exe    phi_Duan_PR_EQ
..\x64\ClrRelease\phreeqc.exe    PR_EQ
..\x64\ClrRelease\phreeqc.exe    PR_EQ_GP
..\x64\ClrRelease\phreeqc.exe    PR_equil
..\x64\ClrRelease\phreeqc.exe    PR_equil2
..\x64\ClrRelease\phreeqc.exe    PR_mx_new
..\x64\ClrRelease\phreeqc.exe    PR_initial_gas
..\x64\ClrRelease\phreeqc.exe    PR_initial_gas_noredox
..\x64\ClrRelease\phreeqc.exe    PR_mx_new
..\x64\ClrRelease\phreeqc.exe    ternary
..\x64\ClrRelease\phreeqc.exe    water_vp1
