..\x64\ClrRelease\phreeqc.exe Apelbl_Na2CO3
..\x64\ClrRelease\phreeqc.exe mV_SO4_rho
..\x64\ClrRelease\phreeqc.exe mV1_rho
..\x64\ClrRelease\phreeqc.exe mV2_rho
..\x64\ClrRelease\phreeqc.exe pKw
..\x64\ClrRelease\phreeqc.exe Vm_BaCl2_sol
..\x64\ClrRelease\phreeqc.exe Vm_CaCl2_sol
..\x64\ClrRelease\phreeqc.exe Vm_HCl_sol
..\x64\ClrRelease\phreeqc.exe Vm_KCl_sol
..\x64\ClrRelease\phreeqc.exe Vm_KHCO3_sol
..\x64\ClrRelease\phreeqc.exe Vm_MgCl2_sol
..\x64\ClrRelease\phreeqc.exe Vm_Na2CO3_sol
..\x64\ClrRelease\phreeqc.exe Vm_Na2SO4_sol
..\x64\ClrRelease\phreeqc.exe Vm_NaCl_sol
..\x64\ClrRelease\phreeqc.exe Vm_NaHCO3_sol
..\x64\ClrRelease\phreeqc.exe Vm_NaNO3_sol
..\x64\ClrRelease\phreeqc.exe Vm_NH4Cl_sol
..\x64\ClrRelease\phreeqc.exe Vm_salt
..\x64\ClrRelease\phreeqc.exe Vm_salt_65
..\x64\ClrRelease\phreeqc.exe Vm_salt_fig
..\x64\ClrRelease\phreeqc.exe Vm_SrCl2_sol
..\x64\ClrRelease\phreeqc.exe Vm0_tc
..\x64\ClrRelease\phreeqc.exe y_H2O
..\x64\ClrRelease\phreeqc.exe rho_H3PO4
