..\x64\ClrRelease\phreeqc.exe    Barite_MCl2 
..\x64\ClrRelease\phreeqc.exe    Barite_NaCl 
..\x64\ClrRelease\phreeqc.exe    Barite_tc 
..\x64\ClrRelease\phreeqc.exe    cc_P 
..\x64\ClrRelease\phreeqc.exe    cc_P0 
..\x64\ClrRelease\phreeqc.exe    cc_P2 
..\x64\ClrRelease\phreeqc.exe    cc_P3 
..\x64\ClrRelease\phreeqc.exe    cc_1barCO2
..\x64\ClrRelease\phreeqc.exe    CO2_4M_NaCl 
..\x64\ClrRelease\phreeqc.exe    CO2_Na2SO4 
..\x64\ClrRelease\phreeqc.exe    co2_t30 
..\x64\ClrRelease\phreeqc.exe    co2_tc 
..\x64\ClrRelease\phreeqc.exe    evap_sea 
..\x64\ClrRelease\phreeqc.exe    gypsum_P 
..\x64\ClrRelease\phreeqc.exe    gypsum_P2 
..\x64\ClrRelease\phreeqc.exe    halite 
..\x64\ClrRelease\phreeqc.exe    P_CO2_Na2SO4 
..\x64\ClrRelease\phreeqc.exe    rho_CaKMgNaCl
..\x64\ClrRelease\phreeqc.exe    rho_CaNaCl
..\x64\ClrRelease\phreeqc.exe    rho_MgCaCl
..\x64\ClrRelease\phreeqc.exe    rho_MgNaCl
..\x64\ClrRelease\phreeqc.exe    rho25
..\x64\ClrRelease\phreeqc.exe    seaw_anhyd 
..\x64\ClrRelease\phreeqc.exe    SrSO4_P
..\x64\ClrRelease\phreeqc.exe    SrSO4_tc
..\x64\ClrRelease\phreeqc.exe    t2
..\x64\ClrRelease\phreeqc.exe    water_vp
..\x64\ClrRelease\phreeqc.exe    Carnallite 
..\x64\ClrRelease\phreeqc.exe    K2SO4
..\x64\ClrRelease\phreeqc.exe    KCl
..\x64\ClrRelease\phreeqc.exe    KCl-SO4
..\x64\ClrRelease\phreeqc.exe    MgCl2
..\x64\ClrRelease\phreeqc.exe    MgCl-SO4
..\x64\ClrRelease\phreeqc.exe    MgSO4
..\x64\ClrRelease\phreeqc.exe    Na2SO4
..\x64\ClrRelease\phreeqc.exe    Na2SO4_phr
..\x64\ClrRelease\phreeqc.exe    NaCl_temp
..\x64\ClrRelease\phreeqc.exe    NaCl-SO4
..\x64\ClrRelease\phreeqc.exe    NaKCl
..\x64\ClrRelease\phreeqc.exe    NaMgCl
..\x64\ClrRelease\phreeqc.exe    anhy_K2SO4
..\x64\ClrRelease\phreeqc.exe    anhy_Na2SO4
..\x64\ClrRelease\phreeqc.exe    anhy_NaCl
..\x64\ClrRelease\phreeqc.exe    gyps_Na2SO4
..\x64\ClrRelease\phreeqc.exe    gyps_NaCl
..\x64\ClrRelease\phreeqc.exe    gypsum