..\ClrClass_release\phreeqcpp.exe    Barite_MCl2 
..\ClrClass_release\phreeqcpp.exe    Barite_NaCl 
..\ClrClass_release\phreeqcpp.exe    Barite_tc 
..\ClrClass_release\phreeqcpp.exe    cc_P 
..\ClrClass_release\phreeqcpp.exe    cc_P0 
..\ClrClass_release\phreeqcpp.exe    cc_P2 
..\ClrClass_release\phreeqcpp.exe    cc_P3 
..\ClrClass_release\phreeqcpp.exe    CO2_4M_NaCl 
..\ClrClass_release\phreeqcpp.exe    CO2_Na2SO4 
..\ClrClass_release\phreeqcpp.exe    co2_t30 
..\ClrClass_release\phreeqcpp.exe    co2_tc 
..\ClrClass_release\phreeqcpp.exe    evap_sea 
..\ClrClass_release\phreeqcpp.exe    gypsum_P 
..\ClrClass_release\phreeqcpp.exe    gypsum_P2 
..\ClrClass_release\phreeqcpp.exe    halite 
..\ClrClass_release\phreeqcpp.exe    P_CO2_Na2SO4 
..\ClrClass_release\phreeqcpp.exe    rho_CaNaCl
..\ClrClass_release\phreeqcpp.exe    rho_MgCaCl
..\ClrClass_release\phreeqcpp.exe    rho_MgNaCl
..\ClrClass_release\phreeqcpp.exe    seaw_anhyd 
..\ClrClass_release\phreeqcpp.exe    SrSO4_P
..\ClrClass_release\phreeqcpp.exe    SrSO4_tc
..\ClrClass_release\phreeqcpp.exe    water_vp
