..\ClrRelease\phreeqc.exe    Barite_MCl2 
..\ClrRelease\phreeqc.exe    Barite_NaCl 
..\ClrRelease\phreeqc.exe    Barite_tc 
..\ClrRelease\phreeqc.exe    cc_P 
..\ClrRelease\phreeqc.exe    cc_P0 
..\ClrRelease\phreeqc.exe    cc_P2 
..\ClrRelease\phreeqc.exe    cc_P3 
..\ClrRelease\phreeqc.exe    cc_1barCO2
..\ClrRelease\phreeqc.exe    CO2_4M_NaCl 
..\ClrRelease\phreeqc.exe    CO2_Na2SO4 
..\ClrRelease\phreeqc.exe    co2_t30 
..\ClrRelease\phreeqc.exe    co2_tc 
..\ClrRelease\phreeqc.exe    evap_sea 
..\ClrRelease\phreeqc.exe    gypsum_P 
..\ClrRelease\phreeqc.exe    gypsum_P2 
..\ClrRelease\phreeqc.exe    halite 
..\ClrRelease\phreeqc.exe    P_CO2_Na2SO4 
..\ClrRelease\phreeqc.exe    rho_CaKMgNaCl
..\ClrRelease\phreeqc.exe    rho_CaNaCl
..\ClrRelease\phreeqc.exe    rho_MgCaCl
..\ClrRelease\phreeqc.exe    rho_MgNaCl
..\ClrRelease\phreeqc.exe    rho25
..\ClrRelease\phreeqc.exe    seaw_anhyd 
..\ClrRelease\phreeqc.exe    SrSO4_P
..\ClrRelease\phreeqc.exe    SrSO4_tc
..\ClrRelease\phreeqc.exe    t2
..\ClrRelease\phreeqc.exe    water_vp
..\ClrRelease\phreeqc.exe    Carnallite 
..\ClrRelease\phreeqc.exe    K2SO4
..\ClrRelease\phreeqc.exe    KCl
..\ClrRelease\phreeqc.exe    KCl-SO4
..\ClrRelease\phreeqc.exe    MgCl2
..\ClrRelease\phreeqc.exe    MgCl-SO4
..\ClrRelease\phreeqc.exe    MgSO4
..\ClrRelease\phreeqc.exe    Na2SO4
..\ClrRelease\phreeqc.exe    Na2SO4_phr
..\ClrRelease\phreeqc.exe    NaCl_temp
..\ClrRelease\phreeqc.exe    NaCl-SO4
..\ClrRelease\phreeqc.exe    NaKCl
..\ClrRelease\phreeqc.exe    NaMgCl
..\ClrRelease\phreeqc.exe    anhy_K2SO4
..\ClrRelease\phreeqc.exe    anhy_Na2SO4
..\ClrRelease\phreeqc.exe    anhy_NaCl
..\ClrRelease\phreeqc.exe    gyps_Na2SO4
..\ClrRelease\phreeqc.exe    gyps_NaCl
..\ClrRelease\phreeqc.exe    gypsum