.\phreeqc.exe K2SO4
.\phreeqc.exe MgSO4
.\phreeqc.exe Na2SO4
.\phreeqc.exe Ca_Na_K_Clmix
.\phreeqc.exe CaCl2_P_T
.\phreeqc.exe Goldsack
.\phreeqc.exe HNaK_Cl
.\phreeqc.exe NaK_ClSO4
.\phreeqc.exe NaK_Mg_ClSO4
.\phreeqc.exe NaKCl_Lang
.\phreeqc.exe NaNH4K_ClBrSO4
.\phreeqc.exe Ruby
.\phreeqc.exe seaw
.\phreeqc.exe seaw_0_200C
.\phreeqc.exe seaw_Fabuss
.\phreeqc.exe v_TP_K2SO4
.\phreeqc.exe v_TP_MgSO4
.\phreeqc.exe v_TP_Na2SO4
.\phreeqc.exe visc_MgSO4
.\phreeqc.exe visc_NaK2SO4
.\phreeqc.exe Yang_mix
.\phreeqc.exe Zhang_mix
