2.14               # File format
1. Solution 34
          -nan     # C
          -nan     # S
          -nan     # CA
          -nan     # AL
          -nan     # MG
          -nan     # NA
          -nan     # K
          -nan     # CL
          -nan     # F
          -nan     # SI
          -nan     # BR
          -nan     # B
          -nan     # BA
          -nan     # LI
          -nan     # SR
          -nan     # FE
          -nan     # MN
          -nan     # N
          -nan     # P
            25     # TEMP
          -nan     # H2S
          -nan     # SO4
             0*    # N15
          -nan     # RS of N
          -nan     # DOX
       4.80483     # HCO3
             6     # PH
           inf     # H2CO3
    0.00839547     # CO3
           inf     # CARBONATES
          -nan     # FE2+
          -nan     # FE3+
          -nan     # MN2+
          -nan     # MN3+
             0*    # MN6+
             0*    # MN7+
          -nan     # CH4
             0*    # DOC
             0*    # RS OF DOC
             0*    # BLANK
          -nan     # C13
          -nan     # C14
             0*    # SR87
             0*    # D
             0*    # O-18
             0*    # TRITIUM
             0*    # 34SSO4
             0*    # 34SH2S
             1     # Well number
1.  01S-02E-01 DCB 1 Harrison, Nace 
          -nan     # C
          -nan     # S
           inf     # CA
          -nan     # AL
           inf     # MG
           inf     # NA
           inf     # K
           inf     # CL
           inf     # F
          -nan     # SI
           inf     # BR
          -nan     # B
           inf     # BA
           inf     # LI
           inf     # SR
          -nan     # FE
          -nan     # MN
          -nan     # N
          -nan     # P
          33.1     # TEMP
          -nan     # H2S
           inf     # SO4
             0*    # N15
          -nan     # RS of N
          -nan     # DOX
       4.80483     # HCO3
           6.5     # PH
           inf     # H2CO3
    0.00839547     # CO3
           inf     # CARBONATES
          -nan     # FE2+
          -nan     # FE3+
          -nan     # MN2+
          -nan     # MN3+
             0*    # MN6+
             0*    # MN7+
          -nan     # CH4
             0*    # DOC
             0*    # RS OF DOC
             0*    # BLANK
          -nan     # C13
          -nan     # C14
             0*    # SR87
          -nan     # D
          -nan     # O-18
             0*    # TRITIUM
             0*    # 34SSO4
             0*    # 34SH2S
             2     # Well number
1.  01S-03E-03 ABA 1        Vendome Well 
          -nan     # C
          -nan     # S
           inf     # CA
          -nan     # AL
           inf     # MG
           inf     # NA
           inf     # K
           inf     # CL
           inf     # F
          -nan     # SI
           inf     # BR
          -nan     # B
           inf     # BA
           inf     # LI
           inf     # SR
          -nan     # FE
          -nan     # MN
          -nan     # N
          -nan     # P
          19.6     # TEMP
          -nan     # H2S
           inf     # SO4
             0*    # N15
          -nan     # RS of N
          -nan     # DOX
       4.80483     # HCO3
          7.14     # PH
           inf     # H2CO3
    0.00839547     # CO3
           inf     # CARBONATES
          -nan     # FE2+
          -nan     # FE3+
          -nan     # MN2+
          -nan     # MN3+
             0*    # MN6+
             0*    # MN7+
          -nan     # CH4
             0*    # DOC
             0*    # RS OF DOC
             0*    # BLANK
          -nan     # C13
          -nan     # C14
             0*    # SR87
          -nan     # D
          -nan     # O-18
             0*    # TRITIUM
             0*    # 34SSO4
             0*    # 34SH2S
             3     # Well number
2. Solution after simulation 3.
          -nan     # C
          -nan     # S
           inf     # CA
          -nan     # AL
           inf     # MG
           inf     # NA
           inf     # K
           inf     # CL
          -nan     # F
          -nan     # SI
          -nan     # BR
          -nan     # B
          -nan     # BA
          -nan     # LI
          -nan     # SR
          -nan     # FE
          -nan     # MN
          -nan     # N
          -nan     # P
            17     # TEMP
          -nan     # H2S
           inf     # SO4
             0*    # N15
          -nan     # RS of N
           inf     # DOX
       4.80483     # HCO3
       7.10242     # PH
           inf     # H2CO3
    0.00839547     # CO3
           inf     # CARBONATES
          -nan     # FE2+
          -nan     # FE3+
          -nan     # MN2+
          -nan     # MN3+
             0*    # MN6+
             0*    # MN7+
          -nan     # CH4
             0*    # DOC
             0*    # RS OF DOC
             0*    # BLANK
          -nan     # C13
          -nan     # C14
             0*    # SR87
             0*    # D
             0*    # O-18
             0*    # TRITIUM
             0*    # 34SSO4
             0*    # 34SH2S
             4     # Well number
2.  01S-02E-01 DCB 1 Harrison, Nace 
          -nan     # C
          -nan     # S
           inf     # CA
          -nan     # AL
           inf     # MG
           inf     # NA
           inf     # K
           inf     # CL
           inf     # F
          -nan     # SI
           inf     # BR
          -nan     # B
           inf     # BA
           inf     # LI
           inf     # SR
          -nan     # FE
          -nan     # MN
          -nan     # N
          -nan     # P
          33.1     # TEMP
          -nan     # H2S
           inf     # SO4
             0*    # N15
          -nan     # RS of N
          -nan     # DOX
       4.80483     # HCO3
           6.5     # PH
           inf     # H2CO3
    0.00839547     # CO3
           inf     # CARBONATES
          -nan     # FE2+
          -nan     # FE3+
          -nan     # MN2+
          -nan     # MN3+
             0*    # MN6+
             0*    # MN7+
          -nan     # CH4
             0*    # DOC
             0*    # RS OF DOC
             0*    # BLANK
          -nan     # C13
          -nan     # C14
             0*    # SR87
          -nan     # D
          -nan     # O-18
             0*    # TRITIUM
             0*    # 34SSO4
             0*    # 34SH2S
             5     # Well number
2.  01S-03E-03 ABA 1        Vendome Well 
          -nan     # C
          -nan     # S
           inf     # CA
          -nan     # AL
           inf     # MG
           inf     # NA
           inf     # K
           inf     # CL
           inf     # F
          -nan     # SI
           inf     # BR
          -nan     # B
           inf     # BA
           inf     # LI
           inf     # SR
          -nan     # FE
          -nan     # MN
          -nan     # N
          -nan     # P
          19.6     # TEMP
          -nan     # H2S
           inf     # SO4
             0*    # N15
          -nan     # RS of N
          -nan     # DOX
       4.80483     # HCO3
          7.14     # PH
           inf     # H2CO3
    0.00839547     # CO3
           inf     # CARBONATES
          -nan     # FE2+
          -nan     # FE3+
          -nan     # MN2+
          -nan     # MN3+
             0*    # MN6+
             0*    # MN7+
          -nan     # CH4
             0*    # DOC
             0*    # RS OF DOC
             0*    # BLANK
          -nan     # C13
          -nan     # C14
             0*    # SR87
          -nan     # D
          -nan     # O-18
             0*    # TRITIUM
             0*    # 34SSO4
             0*    # 34SH2S
             6     # Well number
